services:
  gateway:
    image: caddy:2.8-alpine
    ports: [80:80, 443:443]
    cap_add: [NET_ADMIN]
    restart: unless-stopped
    env_file: [.env]
    environment:
      - CADDY_ADMIN=0.0.0.0:2019
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config

  web:
    image: ghcr.io/clayenkitten/smolathon2:${DEPLOY_TAG}
    build: ./web
    init: true
    expose: [3000]
    restart: unless-stopped
    env_file: [.env]
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:3000/healthz || exit 1"] 
      interval: 5s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:16
    expose: [5432]
    shm_size: 128mb
    restart: unless-stopped
    env_file: [.env]
    volumes:
      - postgres:/var/lib/postgresql/data

  minio:
    image: quay.io/minio/minio:RELEASE.2024-09-22T00-33-43Z
    expose: [9000, 9001]
    command: server --console-address ":9001" /mnt/data
    environment:
      MINIO_VOLUMES: /mnt/data
    env_file: [.env]
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5

  dbgate:
    image: dbgate/dbgate:5.3.1-alpine
    expose: [3000]
    restart: unless-stopped
    env_file: [.env]
    environment:
      CONNECTIONS: main
      SIGNLE_CONNECTION: main
      SINGLE_DATABASE: ${POSTGRES_DB}

      LABEL_main: Main
      SERVER_main: ${POSTGRES_HOST}
      DATABASE_main: ${POSTGRES_DB}
      USER_main: ${POSTGRES_USER}
      PASSWORD_main: ${POSTGRES_PASSWORD}
      PORT_main: 5432
      ENGINE_main: postgres@dbgate-plugin-postgres
    volumes:
      - dbgate:/root/.dbgate

  nforwardauth:
    image: nosduco/nforwardauth:v1
    expose: [3000]
    environment:
      AUTH_HOST: auth.admin.${DOMAIN}
      TOKEN_SECRET: $NFORWARDAUTH_TOKEN_SECRET
      RATE_LIMITER_ENABLED: "true"
      RATE_LIMITER_MAX_RETRIES: 10
      RATE_LIMITER_FIND_TIME: 60
      RATE_LIMITER_BAN_TIME: 60
    volumes:
      - "${PWD}/.passwd:/passwd:ro"

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    expose: [3000]
    volumes:
      - ./homepage/settings.yaml:/app/config/settings.yaml
      - ./homepage/services.yaml:/app/config/services.yaml
      - ./homepage/bookmarks.yaml:/app/config/bookmarks.yaml
      - ./homepage/widgets.yaml:/app/config/widgets.yaml
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      HOMEPAGE_VAR_PROTOCOL: https
      HOMEPAGE_VAR_DOMAIN: $DOMAIN

volumes:
  caddy_data:
  caddy_config:
  postgres:
  dbgate:
  minio:
