services:
  gateway:
    image: caddy:2.8-alpine
    ports: [3000:3000]
    cap_add: [NET_ADMIN]
    restart: unless-stopped
    env_file: [.env]
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    environment:
      DOMAIN: "localhost"

  web:
    build:
      context: ../web
      dockerfile: ../.devcontainer/Dockerfile
    expose: [3000]
    env_file: [../.env]
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - ..:/app:cached

  postgres:
    extends:
      service: postgres
      file: ../compose.yaml

  init-db:
    extends:
      service: init-db
      file: ../compose.yaml

  dbgate:
    extends:
      service: dbgate
      file: ../compose.yaml

  minio:
    extends:
      service: minio
      file: ../compose.yaml

  init-s3:
    extends:
      service: init-s3
      file: ../compose.yaml

  homepage:
    extends:
      service: homepage
      file: ../compose.yaml
    environment:
      HOMEPAGE_VAR_PROTOCOL: http
      HOMEPAGE_VAR_DOMAIN: $DOMAIN:3000

volumes:
  caddy_data:
  caddy_config:
  postgres:
  dbgate:
  minio:
